name: Git checkout github action

on:
  push:
    branches:
      - main
      - rec

jobs:
  post_request:
    runs-on: ubuntu-latest

    steps:
      - name: Print branch name
        run: echo ${{github.ref_name}}

      - name: Main branch git-checkout request
        if: ${{ github.ref_name == 'main' }}
        run: |
          curl -X POST -H "Content-Type: application/json" \
            --user username:password \
            https://training.dev.simplicite.io/api/ext/TrnGitCheckoutService

      - name: Rec branch git-checkout request
        if: ${{ github.ref_name == 'rec' }}
        run: |
          curl -X POST -H "Content-Type: application/json" \
            --user username:password \
            https://trainingrec.dev.simplicite.io/api/ext/TrnGitCheckoutService