name: Main branch git-checkout

on:
  push:
    branches:
      - main

jobs:
  post_request:
    runs-on: ubuntu-latest

    steps:
      - name: Main branch git-checkout request
        run: |
          curl -X POST -H "Content-Type: application/json" \
            --user username:password \
            https://training.dev.simplicite.io/api/ext/TrnGitCheckoutService